### ISSUE TITLE
Summarization Model Checkpoint

### ISSUE THREAD

**Issue by anton164** [mcao516/EntFA#1]
Was the conditional masked language model checkpoint in the description used to generate the summaries included in `data/test.json` / `data/train.json`? If not, would it be possible to have the checkpoint that you used for generating summaries?

**Comment by mcao516** [comment]
Hi, for summary generation, we use the official fairseq `bart.large` checkpoint which you can find [here](https://github.com/pytorch/fairseq/tree/main/examples/bart).

**Comment by anton164** [comment]
Thanks for the clarification!
