### ISSUE TITLE
Paper clarification for training CMLM

### ISSUE THREAD

**Issue by anton164** [mcao516/EntFA#4]
In the paper you say:
> For training the CMLM, we use both XSUM and the CNN/Dailymail dataset.

Do you train the CMLM separately for each dataset depending on the downstream task, or do you train one CMLM using both datasets?

**Comment by mcao516** [comment]
Hi Anton, we train the CMLM separately for each dataset.

**Comment by anton164** [comment]
Thanks @mcao516 !
